USE [rmA_Main]
GO

/****** Object:  View [ARCH].[vw_DataStore_ClaimLitigation]    Script Date: 11/8/2023 9:06:36 PM ******/
DROP VIEW [ARCH].[vw_DataStore_ClaimLitigation]
GO

/****** Object:  View [ARCH].[vw_DataStore_ClaimLitigation]    Script Date: 11/8/2023 9:06:36 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO








CREATE VIEW [ARCH].[vw_DataStore_ClaimLitigation]
AS


-- Description:  RMA CLAIM Litigation source abstraction query
--
-- Modification History:
--
-- Ver		When		Who				What
-- v1.01	2023-07-20	ADsouza			- Initial Version (similar to CLAIM View for all base common fields) + Added Matter Number

SELECT 
	"X"."ROW_TYP_NM",
	"X"."SRC_SYS_CD",
	"X"."BUS_UNIT_CD",
	"X"."CLMNT_KEY",
	"X"."CLM_KEY",
	"X"."LYR_KEY",
	"X"."POL_KEY",
	DATEADD(ms, 
				10 * (row_number() 
					  over (
							partition by 
							 "X"."CLM_NUM",
							"X"."ORIG_ROW_UPDT_TS" -- ORIG ROW_UPDT_TS
							order by "X"."CLM_KEY"
							)-1
					  ), 
					"X"."ORIG_ROW_UPDT_TS"
				) AS "ROW_UPDT_TS",	
	"X"."CLMNT_NUM",
	"X"."CLM_NUM",
	"X"."LYR_NUM",
	"X"."POL_NUM",
	"X"."POL_EFF_DT",
	"X"."POL_ORIG_SRC_CD",
	"X"."MATTER_NUM",
	"X"."MATTER_NM",
	"X"."MATTER_CREATE_DT",
	"X"."HIRED_FIRM_NM",
	"X"."LAW_FIRM_RT_CD",
	"X"."LEAD_ATTY_NM",
	"X"."CLMNT_LAW_FIRM_NM",
	"X"."CASE_TYP",
	"X"."MATTER_STATE_CD",
	"X"."FEDERAL_DISTRICT_NM",
	"X"."COUNTY_NM",
	"X"."ISSUE_IN_DISPUTE_DESC",
	"X"."JURISDICTION_DESC",
	"X"."COURT_VENUE_NM"

FROM
	(				
		SELECT
		 'ClaimLitigation' AS "ROW_TYP_NM"
		, 'RMA' AS "SRC_SYS_CD"
		, 'ALL' AS "BUS_UNIT_CD"
		, concat ('RMA-ALL-', concat (CAST("CLAIM_X_LITIGATION"."CLAIM_ID" AS VARCHAR), '-', CAST("CLAIM_X_LITIGATION"."CLAIMANT_EID" AS VARCHAR))) AS "CLMNT_KEY"
		, concat ('RMA-ALL-', CAST("CLAIM_X_LITIGATION"."CLAIM_ID" AS VARCHAR)) AS "CLM_KEY"
		, NULL AS "POL_KEY"
		, NULL AS "LYR_KEY"
		, "CATASTROPHE"."CATASTROPHE_ROW_ID" AS "CATSRPH_KEY" 
		,   
			(
				SELECT
					CAST
						(
							CASE 
								WHEN "X"."MAXV" is NULL then NULL 
								else 
								concat(substring("X"."MAXV", 1, 4), '-', substring("X"."MAXV", 5, 2), '-', substring("X"."MAXV", 7, 2), 
								' ', substring("X"."MAXV", 9, 2), ':', substring("X"."MAXV", 11, 2), ':', substring("X"."MAXV", 13, 2))
							END
											AS datetime
									) "X"
								 FROM
									(
										SELECT MAX("VS"."V") AS "MAXV"
											FROM (
												  VALUES (isNULL("CLAIM"."DTTM_RCD_LAST_UPD", '19000101000000')),
														(isNULL("EVENT"."DTTM_RCD_LAST_UPD", '19000101000000')),
														(isNULL("POLICY"."DTTM_RCD_LAST_UPD", '19000101000000')),
														(isNULL("CLAIM_ADJUSTER"."DTTM_RCD_LAST_UPD", '19000101000000')),
														(isNULL("ADJUSTER"."DTTM_RCD_LAST_UPD", '19000101000000')),
														(isNULL("CLAIM_X_PROPERTYLOSS"."DTTM_RCD_LAST_UPD", '19000101000000')),
														(isNULL("PROPERTY_UNIT"."DTTM_RCD_LAST_UPD", '19000101000000'))
												  )  AS "VS"("V")
									) "X"
					) AS "ORIG_ROW_UPDT_TS"
	, NULL AS "PARENT_CLM_KEY"
	, "CLAIM"."CLAIM_NUMBER" AS "CLM_NUM"
	,
	    CASE
			WHEN "CLAIM"."DATE_OF_CLAIM" is NULL THEN NULL
	        ELSE 
				CAST(concat(substring("CLAIM"."DATE_OF_CLAIM", 1, 4), '-', substring("CLAIM"."DATE_OF_CLAIM", 5, 2), '-', substring("CLAIM"."DATE_OF_CLAIM", 7, 2)) AS date)
		END AS "CLM_REPRTD_DT"

	, NULL AS "PARENT_CLM_NUM"
	, "CLAIMANT"."CLAIMANT_NUMBER" AS "CLMNT_NUM"
	, "POLICY"."POLICY_NAME" AS "POL_NUM"
	,
       CASE
			WHEN "POLICY"."EFFECTIVE_DATE" is NULL THEN NULL
	        ELSE CAST(concat(substring("POLICY"."EFFECTIVE_DATE", 1, 4), '-', substring("POLICY"."EFFECTIVE_DATE", 5, 2), '-', substring("POLICY"."EFFECTIVE_DATE", 7, 2)) AS date)
		END AS "POL_EFF_DT"
	,
		CASE 
			WHEN "POLICY"."ISSUE_SYSTEM" = 'PIJ' THEN 'Arch' 
			ELSE 'MGA' 
		END AS "POL_ORIG_SRC_CD"
	, NULL AS "LYR_NUM"
	--, "CLAIM_X_LITIGATION"."DOCKET_NUMBER" AS "MATTER_NUM"
	, "LITIGATION_SUPP"."LSS_MATTER_ID" AS "MATTER_NUM"
	, "CLAIM_X_LITIGATION"."MATTER_NAME" AS "MATTER_NM"
	, "CLAIM_X_LITIGATION"."MATTER_CREATION_DATE" AS "MATTER_CREATE_DT"
	, "LITIGATION_SUPP"."LIT_HIRDFRM_TEXT" AS "HIRED_FIRM_NM"
	, concat("LAW_FIRM_RT_CD"."SHORT_CODE",' ',"LAW_FIRM_RT_CD"."CODE_DESC") AS "LAW_FIRM_RT_CD"
	, "LITIGATION_SUPP"."LIT_LEADATY_TEXT" AS "LEAD_ATTY_NM"
	, "LITIGATION_SUPP"."CLMNT_FIRM_TEXT" AS "CLMNT_LAW_FIRM_NM"
	, "CLAIM_X_LITIGATION"."CASE_TYPE" AS "CASE_TYP"
	, concat("STATE"."STATE_ID",' ',"STATE"."STATE_NAME") AS "MATTER_STATE_CD"
	, "CLAIM_X_LITIGATION"."FEDERAL_DISTRICT" AS "FEDERAL_DISTRICT_NM"
	, "CLAIM_X_LITIGATION"."COUNTY" AS "COUNTY_NM"
	, "CLAIM_X_LITIGATION"."ISSUE_IN_DISPUTE" AS "ISSUE_IN_DISPUTE_DESC"
	, "CLAIM_X_LITIGATION"."JURISDICTION" AS "JURISDICTION_DESC"
	, "CLAIM_X_LITIGATION"."COURT_NAME" AS "COURT_VENUE_NM"


	FROM "rmA_main"."dbo"."CLAIM_X_LITIGATION" "CLAIM_X_LITIGATION" 
	LEFT JOIN "rmA_main"."dbo"."CLAIM" "CLAIM" (NOLOCK) ON "CLAIM_X_LITIGATION"."CLAIM_ID"="CLAIM"."CLAIM_ID"
	LEFT JOIN "rmA_main"."dbo"."CLAIM_SUPP" "CLAIM_SUPP" (NOLOCK) ON  "CLAIM"."CLAIM_ID" = "CLAIM_SUPP"."CLAIM_ID" 
	LEFT JOIN "rmA_main"."dbo"."EVENT" "EVENT" (NOLOCK) ON "CLAIM"."EVENT_ID" = "EVENT"."EVENT_ID"
	LEFT JOIN "rmA_main"."dbo"."POLICY" "POLICY" (NOLOCK) ON "POLICY"."POLICY_ID" = "CLAIM"."PRIMARY_POLICY_ID"
	LEFT JOIN "rmA_main"."dbo"."CATASTROPHE" "CATASTROPHE" (NOLOCK) ON "CLAIM"."CATASTROPHE_ROW_ID" = "CATASTROPHE"."CATASTROPHE_ROW_ID"
	LEFT JOIN (SELECT "CLAIM_ID",  MIN("ROW_ID") "ROW_ID"
			FROM "rmA_main"."dbo"."CLAIM_X_PROPERTYLOSS" "CLAIM_X_PROPERTYLOSS" (NOLOCK) WHERE "INSURED" = -1
			GROUP BY  "CLAIM_ID") "CLAIM_X_PROPERTYLOSS_Ctrl" ON "CLAIM_X_PROPERTYLOSS_Ctrl"."CLAIM_ID" = "CLAIM"."CLAIM_ID"
	LEFT JOIN "rmA_main"."dbo"."CLAIM_X_PROPERTYLOSS" "CLAIM_X_PROPERTYLOSS" (NOLOCK) ON "CLAIM_X_PROPERTYLOSS"."ROW_ID" = "CLAIM_X_PROPERTYLOSS_Ctrl"."ROW_ID" 
	LEFT JOIN "rmA_main"."dbo"."PROPERTY_UNIT" "PROPERTY_UNIT" (NOLOCK) ON  "PROPERTY_UNIT"."PROPERTY_ID" = "CLAIM_X_PROPERTYLOSS"."PROPERTY_ID" 
	LEFT JOIN "rmA_main"."dbo"."CLAIM_ADJUSTER" "CLAIM_ADJUSTER" (NOLOCK)  ON "CLAIM_ADJUSTER"."CLAIM_ID" = "CLAIM"."CLAIM_ID" AND "CLAIM_ADJUSTER"."CURRENT_ADJ_FLAG" = -1
	LEFT JOIN "rmA_main"."dbo"."ENTITY" "ADJUSTER" (NOLOCK) ON "ADJUSTER"."ENTITY_ID" = "CLAIM_ADJUSTER"."ADJUSTER_EID"	
	LEFT JOIN "rmA_main"."dbo"."LITIGATION_SUPP" "LITIGATION_SUPP" (NOLOCK) ON "LITIGATION_SUPP"."LITIGATION_ROW_ID"="CLAIM_X_LITIGATION"."LITIGATION_ROW_ID"
	LEFT JOIN "rmA_main"."dbo"."STATES" "STATE" ON  "STATE"."STATE_ROW_ID" = "CLAIM_X_LITIGATION"."VENUE_STATE_ID"
	LEFT JOIN "rmA_main"."dbo"."CODES_TEXT" "LAW_FIRM_RT_CD" (NOLOCK) ON "LAW_FIRM_RT_CD"."CODE_ID" = "LITIGATION_SUPP"."LOB_RATE_CD_CODE"
	LEFT JOIN "rmA_Main"."dbo"."CLAIMANT" "CLAIMANT" (NOLOCK) ON "CLAIM_X_LITIGATION"."CLAIM_ID"="CLAIMANT"."CLAIM_ID" AND "CLAIM_X_LITIGATION"."CLAIMANT_EID" = "CLAIMANT"."CLAIMANT_EID"
	
WHERE 1=1 
)"X"

GO


