USE [rmA_Main]
GO

/****** Object:  View [ARCH].[vw_DataStore_ClaimLiabilityLoss]    Script Date: 11/8/2023 9:06:50 PM ******/
DROP VIEW [ARCH].[vw_DataStore_ClaimLiabilityLoss]
GO

/****** Object:  View [ARCH].[vw_DataStore_ClaimLiabilityLoss]    Script Date: 11/8/2023 9:06:50 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO








CREATE VIEW [ARCH].[vw_DataStore_ClaimLiabilityLoss]
AS


-- Description: RMA CLAIM_LIABILITY_LOSS source abstraction query 
--
-- Modification History:
-- Ver		When		Who				What
-- v1.02	2023-09-09	ADsouza		Added CAS check for INJURY_DAMG_TO_TYP_CD and INJURY_DAMG_TO_TYP_DESC fields to map to correct RMA source columns
-- v1.01	2023-05-17	ADsouza		Adding Non-CAS Liability Loss Fields pulled out from Claim Exposure View
-- v1.00	2023-05-03	ADsouza		Initial SQL for Claim Liability Loss Fields pulled out from Claim Exposure View


SELECT 
"EXP"."ROW_TYP_NM",
"EXP"."SRC_SYS_CD",
"EXP"."BUS_UNIT_CD",
"EXP"."CLM_LIABLTY_LOSS_KEY",
"EXP"."CLM_KEY",
"EXP"."ROW_UPDT_TS",
"EXP"."CLM_NUM",
"EXP"."LIABLTY_TYP_CD",
"EXP"."LIABLTY_TYP_DESC",
"EXP"."MLOB_CD",
"EXP"."MLOB_DESC",
"EXP"."MJOR_LOSS_TYP_CD",
"EXP"."MJOR_LOSS_TYP_DESC",
"EXP"."SCNDRY_LOSS_TYP_CD",
"EXP"."SCNDRY_LOSS_TYP_DESC",
"EXP"."INJURY_DAMG_LOC_TYP_CD",
"EXP"."INJURY_DAMG_LOC_TYP_DESC",
"EXP"."PUNITV_DAMG_IND",
"EXP"."LABOR_LAW_CD",
"EXP"."LABOR_LAW_DESC",
"EXP"."LABOR_LAW_STATE_CD",
"EXP"."SUIT_AGAINST_ARCH_CD",
"EXP"."SUIT_AGAINST_ARCH_DESC",
"EXP"."INJURY_DAMG_TYP_CD",
"EXP"."INJURY_DAMG_TYP_DESC",
"EXP"."AREA_OF_PRCTCE_CD",
"EXP"."AREA_OF_PRCTCE_DESC",
"EXP"."PRJCT_TYP_CD",
"EXP"."PRJCT_TYP_DESC",
"EXP"."DISCIPLINE_CD",
"EXP"."DISCIPLINE_DESC",
"EXP"."DAMG_CATGRY_CD",
"EXP"."DAMG_CATGRY_DESC",
"EXP"."CLM_TYP_CD",
"EXP"."CLM_TYP_DESC",
"EXP"."ADDTONL_INS_IND",
"EXP"."COV_EXT_CD",
"EXP"."COV_EXT_DESC",
"EXP"."TENDR_OPRTUNTY_IND",
"EXP"."TENDR_STATUS_CD",
"EXP"."TENDR_STATUS_DESC",
"EXP"."ULTMAT_RESOLTN_AVALBLE_IND",
"EXP"."ULTMAT_RESOLTN_AMT",
"EXP"."CNSTRCTN_DFECT_IND",
"EXP"."OWNER_INTRST_POL_IND",
"EXP"."INJURY_DAMG_TO_TYP_CD",
"EXP"."INJURY_DAMG_TO_TYP_DESC",
--Newly Added
"EXP"."ARCH_LOSS_TYP_CD",
"EXP"."ARCH_LOSS_TYP_DESC",
"EXP"."CLM_NOTFCATN_TYP",
"EXP"."ISO_LOSS_TYP_CD",
"EXP"."ISO_LOSS_TYP_DESC",
"EXP"."CYBER_RELATED",
"EXP"."LIABLTY_COV_TYP_CD",
"EXP"."LIABLTY_COV_TYP_DESC"



FROM
	(
		SELECT 'ClaimLiability' AS "ROW_TYP_NM"
				,'RMA' AS "SRC_SYS_CD"
				,'ALL' AS "BUS_UNIT_CD"
				,CONCAT('RMA-ALL-LIABLOSS-',
					(CASE WHEN "CLAIM"."CLAIM_ID" IS NULL or "CLAIM"."CLAIM_ID"=0 OR "CLAIM"."CLAIM_ID"='' THEN 'No Claim' ELSE
						 "CLAIM"."CLAIM_ID" END), '-',
					(CASE WHEN "CXLL"."ROW_ID" IS NULL OR "CXLL"."ROW_ID"='' 
						THEN '0' ELSE "CXLL"."ROW_ID" END), '-',
					(CASE WHEN "CXLL"."LIABILITY_TYPE_CODE" IS NULL OR "CXLL"."LIABILITY_TYPE_CODE"='' 
						THEN '0' ELSE "CXLL"."LIABILITY_TYPE_CODE" END)
					) AS "CLM_LIABLTY_LOSS_KEY"
  				,concat ('RMA-ALL-', CAST("CLAIM"."CLAIM_ID" AS VARCHAR)) AS "CLM_KEY"
				,(SELECT CAST (CASE WHEN "X"."MAXV" is NULL then NULL
									ELSE
									concat(substring("X"."MAXV", 1, 4), '-', substring("X"."MAXV", 5, 2), '-', substring("X"."MAXV", 7, 2),
									' ', substring("X"."MAXV", 9, 2), ':', substring("X"."MAXV", 11, 2), ':', substring("X"."MAXV", 13, 2))
								END AS datetime) "X"
					FROM (SELECT MAX("VS"."V") AS "MAXV" FROM
						(VALUES
								(isNULL("CLAIM"."DTTM_RCD_LAST_UPD", '19000101000000')),
								(isNULL("EVENT"."DTTM_RCD_LAST_UPD", '19000101000000')),
								(isNULL("CXLL"."DTTM_RCD_LAST_UPD",'19000101000000'))
						) AS "VS"("V")
						) "X"
					) AS "ROW_UPDT_TS"
				, "CLAIM"."CLAIM_NUMBER" AS "CLM_NUM"
				, "LIABLTY_TYP_CD" = "CODES"."SHORT_CODE"
				, "LIABLTY_TYP_DESC" = "CODES"."CODE_DESC"
				, CASE WHEN "CODES"."SHORT_CODE" = 'CA' THEN "CASMLOB"."SHORT_CODE" ELSE "MLOB"."SHORT_CODE" END AS "MLOB_CD"
				, CASE WHEN "CODES"."SHORT_CODE" = 'CA' THEN "CASMLOB"."CODE_DESC" ELSE "MLOB"."CODE_DESC" END AS "MLOB_DESC"
				, "MJOR_LOSS_TYP_CD" = "MAJLOSTYP"."SHORT_CODE"
				, "MJOR_LOSS_TYP_DESC" = "MAJLOSTYP"."CODE_DESC"
				, CASE WHEN "CODES"."SHORT_CODE" = 'CA' THEN "CASSLOS"."SHORT_CODE" ELSE "LSLOS"."SHORT_CODE" END AS "SCNDRY_LOSS_TYP_CD"
				, CASE WHEN "CODES"."SHORT_CODE" = 'CA' THEN "CASSLOS"."CODE_DESC" ELSE "LSLOS"."CODE_DESC" END AS "SCNDRY_LOSS_TYP_DESC"
				, "INJURY_DAMG_LOC_TYP_CD" = "INJLOC"."SHORT_CODE"
				, "INJURY_DAMG_LOC_TYP_DESC" = "INJLOC"."CODE_DESC"
				, CASE WHEN "PUDNAM"."SHORT_CODE" is NULL THEN 'N'   
					WHEN "PUDNAM"."SHORT_CODE"  = 'N' THEN 'N'
					WHEN "PUDNAM"."SHORT_CODE"  = 'Y' THEN 'Y' END AS "PUNITV_DAMG_IND" 
				, "LABOR_LAW_CD" = "LABORLAW"."SHORT_CODE"
				, "LABOR_LAW_DESC" = "LABORLAW"."CODE_DESC"
				, CASE WHEN "LABORLAW"."SHORT_CODE" is Not NULL THEN 'NYLL' ELSE NULL END AS "LABOR_LAW_STATE_CD" -- "NYLL" only if there is a value for "LABOR_LAW_CD" ? Now its just NY, should this be hardcoded or sourced from some table?
				, "SUIT_AGAINST_ARCH_CD" = "SUAGAR"."SHORT_CODE"
				, "SUIT_AGAINST_ARCH_DESC" = "SUAGAR"."CODE_DESC"
				, "INJURY_DAMG_TYP_CD" = "INJACT"."SHORT_CODE"
				, "INJURY_DAMG_TYP_DESC" = "INJACT"."CODE_DESC"
				, "AREA_OF_PRCTCE_CD" = "AOP"."SHORT_CODE"
				, "AREA_OF_PRCTCE_DESC" = "AOP"."CODE_DESC"
				, "PRJCT_TYP_CD" = "PROJTYPE"."SHORT_CODE"
				, "PRJCT_TYP_DESC" = "PROJTYPE"."CODE_DESC"
				, "DISCIPLINE_CD" = "DSCPTY"."SHORT_CODE" 
				, "DISCIPLINE_DESC" = "DSCPTY"."CODE_DESC" 
				, "DAMG_CATGRY_CD" = "DAMCAT"."SHORT_CODE" 
				, "DAMG_CATGRY_DESC" = "DAMCAT"."CODE_DESC"
				, "CLM_TYP_CD" = "CLM_TYPE"."SHORT_CODE"
				, "CLM_TYP_DESC" = "CLM_TYPE"."CODE_DESC"
				, CASE WHEN "COADIN"."SHORT_CODE"  is NULL THEN 'N'
					WHEN "COADIN"."SHORT_CODE"  = 'N' THEN 'N'
					WHEN "COADIN"."SHORT_CODE"  = 'Y' THEN 'Y'
					END AS "ADDTONL_INS_IND" 
				, "COV_EXT_CD" = "COVEXT"."SHORT_CODE"
				, "COV_EXT_DESC" = "COVEXT"."CODE_DESC"
				, CASE WHEN "TENOPP"."SHORT_CODE" is NULL THEN 'N' 
					WHEN "TENOPP"."SHORT_CODE"  = 'N' THEN 'N'
					WHEN "TENOPP"."SHORT_CODE"  = 'Y' THEN 'Y'
					END AS "TENDR_OPRTUNTY_IND"
				, "TENDR_STATUS_CD" = "TENACC"."SHORT_CODE"
				, "TENDR_STATUS_DESC" = "TENACC"."CODE_DESC"
				, CASE WHEN "ULTRES"."SHORT_CODE" is NULL THEN 'N'  
					WHEN "ULTRES"."SHORT_CODE"  = 'N' THEN 'N'
					WHEN "ULTRES"."SHORT_CODE"  = 'Y' THEN 'Y'
					END AS "ULTMAT_RESOLTN_AVALBLE_IND"
				, "ULTMAT_RESOLTN_AMT" = "CXLLS"."LOSS_ULTRES_AMT"
				, CASE WHEN "LOSSCONSTD"."SHORT_CODE" is NULL THEN 'N'  
					WHEN "LOSSCONSTD"."SHORT_CODE"  = 'N' THEN 'N'
					WHEN "LOSSCONSTD"."SHORT_CODE"  = 'Y' THEN 'Y'
					END AS  "CNSTRCTN_DFECT_IND"
				, CASE WHEN "OWNINT"."SHORT_CODE" is NULL THEN 'N'  
					WHEN "OWNINT"."SHORT_CODE"  = 'N' THEN 'N'
					WHEN "OWNINT"."SHORT_CODE"  = 'Y' THEN 'Y'
					END AS "OWNER_INTRST_POL_IND"
				,  CASE WHEN "CODES"."SHORT_CODE" = 'CA' THEN "CASINJDT"."SHORT_CODE" ELSE "INJDT"."SHORT_CODE" END AS "INJURY_DAMG_TO_TYP_CD" 
				,  CASE WHEN "CODES"."SHORT_CODE" = 'CA' THEN "CASINJDT"."CODE_DESC" ELSE "INJDT"."CODE_DESC" END AS "INJURY_DAMG_TO_TYP_DESC" 
				, "ARCH_LOSS_TYP_CD" = "MLOB"."SHORT_CODE"
				, "ARCH_LOSS_TYP_DESC" = "MLOB"."CODE_DESC"
				, "CLM_NOTFCATN_TYP" = "CTYP_1"."CODE_DESC"
				, "ISO_LOSS_TYP_CD" = "LOSSTYPCD"."SHORT_CODE"
				, "ISO_LOSS_TYP_DESC" = "LOSSTYPCD"."CODE_DESC"
				, "CYBER_RELATED" = "CYBREL"."SHORT_CODE"
				, "LIABLTY_COV_TYP_CD" = "CVG_TYP_EA"."SHORT_CODE"
				, "LIABLTY_COV_TYP_DESC" = "CVG_TYP_EA"."CODE_DESC"

		FROM "rmA_Main"."dbo"."CLAIM" "CLAIM" (NOLOCK) 
					JOIN "rmA_main"."dbo"."EVENT" "EVENT" (NOLOCK) ON "CLAIM"."EVENT_ID" ="EVENT"."EVENT_ID"
					JOIN "rmA_main"."dbo"."CLAIM_X_LIABILITYLOSS" "CXLL" (NOLOCK) ON "CLAIM"."CLAIM_ID" =
					"CXLL"."CLAIM_ID"				

	LEFT JOIN "rmA_main"."dbo"."CODES_TEXT" "CODES" ON "CODES"."CODE_ID" = "CXLL"."LIABILITY_TYPE_CODE"
	LEFT JOIN "rmA_main"."dbo"."CLAIM_X_LIABILITYLOSS_SUPP" "CXLLS" ON "CXLL".ROW_ID = "CXLLS"."ROW_ID"
	LEFT JOIN "rmA_main"."dbo"."CODES_TEXT" "MAJLOSTYP" ON "CXLLS"."CAS_MAJ_TYP_CODE" = "MAJLOSTYP"."CODE_ID"
	LEFT JOIN "rmA_main"."dbo"."CODES_TEXT" "MLOB" ON "CXLLS"."MLOB_CODE" = "MLOB"."CODE_ID"
	LEFT JOIN "rmA_main"."dbo"."CODES_TEXT" "LSLOS" ON "CXLLS"."LIAB_SLTYP_CODE" = "LSLOS"."CODE_ID"	
	LEFT JOIN "rmA_main"."dbo"."CODES_TEXT" "CASMLOB" ON "CXLLS"."LIAB_CASMLB_CODE" = "CASMLOB"."CODE_ID"
	LEFT JOIN "rmA_main"."dbo"."CODES_TEXT" "CASSLOS" ON "CXLLS"."CAS_SCNDLOS_CODE" = "CASSLOS"."CODE_ID"
	LEFT JOIN "rmA_main"."dbo"."CODES_TEXT" "INJLOC" ON "CXLLS"."LIAB_INJLOC_CODE"= "INJLOC"."CODE_ID"
	LEFT JOIN "rmA_main"."dbo"."CODES_TEXT" "INJACT" ON "CXLLS"."LIAB_INJACT_CODE"= "INJACT"."CODE_ID"
	LEFT JOIN "rmA_main"."dbo"."CODES_TEXT" "INJDT" ON "CXLLS"."LIAB_CYINTY_CODE"= "INJDT"."CODE_ID"
	LEFT JOIN "rmA_main"."dbo"."CODES_TEXT" "CASINJDT" ON "CXLLS"."LIAB_INJDT_CODE"= "CASINJDT"."CODE_ID"
	LEFT JOIN "rmA_main"."dbo"."CODES_TEXT" "LABORLAW" ON "CXLLS"."LIAB_NYLALA_CODE"="LABORLAW"."CODE_ID"
	LEFT JOIN "rmA_main"."dbo"."CODES_TEXT" "SUAGAR" ON "CXLLS"."LIAB_SUAGAR_CODE"="SUAGAR"."CODE_ID"
	LEFT JOIN "rmA_main"."dbo"."CODES_TEXT" "CLM_TYPE" (NOLOCK) ON "CLM_TYPE"."CODE_ID" = "CLAIM"."CLAIM_TYPE_CODE"
	LEFT JOIN "rmA_main"."dbo"."CODES_TEXT" "COVEXT" ON "CXLLS"."LOSS_COVEXT_CODE"="COVEXT"."CODE_ID"
	LEFT JOIN "rmA_main"."dbo"."CODES_TEXT" "TENOPP" ON "CXLLS"."TENOPP_CODE"="TENOPP"."CODE_ID"
	LEFT JOIN "rmA_main"."dbo"."CODES_TEXT" "TENACC" ON "CXLLS"."LIAB_TENACC_CODE"="TENACC"."CODE_ID"
	LEFT JOIN "rmA_main"."dbo"."CODES_TEXT" "PUDNAM" ON "CXLLS"."LIAB_PUNDAM_CODE"="PUDNAM"."CODE_ID"
	LEFT JOIN "rmA_main"."dbo"."CODES_TEXT" "ULTRES" ON "CXLLS"."LOSS_ULTRES_CODE"="ULTRES"."CODE_ID"
	LEFT JOIN "rmA_main"."dbo"."CODES_TEXT" "LOSSCONSTD" ON "CXLLS"."LOSS_CONSTD_CODE"="LOSSCONSTD"."CODE_ID"
	LEFT JOIN "rmA_main"."dbo"."CODES_TEXT" "COADIN" ON "CXLLS"."LIAB_COADIN_CODE"="COADIN"."CODE_ID"
	LEFT JOIN "rmA_main"."dbo"."CODES_TEXT" "OWNINT" ON "CXLLS"."CAS_OWN_INT_CODE"="OWNINT"."CODE_ID"
	LEFT JOIN "rmA_main"."dbo"."CODES_TEXT" "PROJTYPE" ON "CXLLS"."LIAB_PROJTY_CODE"="PROJTYPE"."CODE_ID"
	LEFT JOIN "rmA_main"."dbo"."CODES_TEXT" "AOP" ON "CXLLS"."LIAB_AOP_CODE"="AOP"."CODE_ID"
	LEFT JOIN "rmA_main"."dbo"."CODES_TEXT" "DAMCAT" ON "CXLLS"."PRP_DMG_TYP_CODE"="DAMCAT"."CODE_ID"
	LEFT JOIN "rmA_main"."dbo"."CODES_TEXT" "DSCPTY" ON "CXLLS"."LIAB_DSCPTY_CODE"="DSCPTY"."CODE_ID"
	LEFT JOIN "rmA_main"."dbo"."CODES_TEXT" "CTYP_1" ON "CXLLS"."LIAB_CTYPE_CODE" = "CTYP_1"."CODE_ID"
	LEFT JOIN "rmA_main"."dbo"."CODES_TEXT" "CYBREL" ON "CXLLS"."EA_CYBERELA_CODE"="CYBREL"."CODE_ID"
	LEFT JOIN "rmA_main"."dbo"."CODES_TEXT" "CVG_TYP_EA" ON "CXLLS"."COVERAGE_CODE" = "CVG_TYP_EA"."CODE_ID"
	LEFT JOIN "rmA_main"."dbo"."CODES_TEXT" "LOSSTYPCD" ON "CXLLS"."LOSS_TYPE_CODE" = "LOSSTYPCD"."CODE_ID"


WHERE 1=1 

	)"EXP"

GO


